# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

RUN apk add --no-cache gcc musl-dev

# Install the project into `/app`
WORKDIR /app

RUN pip install --no-cache-dir "mcp[cli]>=1.6.0"

COPY . /app

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

# Set transport mode to HTTP
ENV TRANSPORT=http

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

# Run the application directly using the venv Python
CMD ["python", "server.py"]
