# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev

# Set work directory
WORKDIR /app

# Copy project files
COPY . /app

# Install required Python package (MCP CLI dependency)
RUN pip install --no-cache-dir "mcp[cli]>=1.6.0"

# Expose the server port if needed, though stdio transport is used

# Command to run the MCP server
CMD ["python", "server.py"]
